### ISSUE TITLE
Keyword argument defaults

### ISSUE THREAD

**Issue by DamirSvrtan** [barsoom/attr_extras#25]
Hi! 👋 

Thank you for creating this library, I've been using it for over a year on most of the stuff I do and it has been great! (99% of time basically using the method object).

I've wanted to ask you, is there an option to pass default values to keyword arguments on method objects?

**Comment by henrik** [comment]
Hi! Thank you so much! :) Appreciate it.

There is currently no support for that, I'm afraid. It's been requested, but it's a bit complicated to get right. Pull requests accepted. I'd love to add it some time, but can't make any promises.

**Comment by henrik** [comment]
Fixed in #26 by @lesin :)
