### ISSUE TITLE
Default values for non-keyword arguments

### ISSUE THREAD

**Issue by dvisockas** [barsoom/attr_extras#32]
Hey,

Is there a reason why only keyword arguments can have default values?
Syntax like:

```
class Make
  attr_initialize :target, params: {}
end
```

would take even more boilerplate out of peoples codebases IMO.

**Comment by henrik** [comment]
Hi! No, no reason I can think of off the top of my head. I'll close this issue since it's been answered, but a PR with good test coverage would be very welcome :)
