### ISSUE TITLE
Warning with Ruby 2.7

### ISSUE THREAD

**Issue by gylaz** [barsoom/attr_extras#33]
Seeings the likes of:

```
...gems/2.7.0/gems/attr_extras-6.2.3/lib/attr_extras/explicit.rb:66: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Any idea if there's a way around it, or how to fix?

**Comment by olleolleolle** [comment]
One way would be to use [the ruby2_keywords gem](https://github.com/ruby/ruby2_keywords/), and "annotate" the methods which this can happen to.

Would you like to make a PR?

**Comment by mcmire** [comment]
#34 should fix this!
