### ISSUE TITLE
Initializing custom variables

### ISSUE THREAD

**Issue by eyalev** [barsoom/attr_extras#4]
Hi,

Is it possible to initialize custom instance variables in addition to using pattr_initialize ?

For example: @time = Time.now

Thanks

**Comment by mcmire** [comment]
@henrik Would it be a good idea for `attr_initialize` and friends to mix in a module so that you can override #initialize and `super` as needed?

**Comment by henrik** [comment]
@mcmire Hm, yeah, maybe. I generally like the flexibility you get by adding functionality through mixing in modules.

We do support a block syntax to do things after assigning values, e.g.

```
pattr_initialize :time do
  @time ||= Time.now
end
```

Which could help in some cases. But in this example, you would still need to pass a `nil` value when you initialize: it doesn't make the argument optional.

We've considered supporting optional arguments, but it's hard to think of a syntax for that that isn't super messy. Currently considering if we should just hijack block parameters:

``` ruby
pattr_initialize { |time=Time.now| }
```
