### ISSUE TITLE
Can't bundle on ruby 3 (sign-post issue, revisit on minitest release)

### ISSUE THREAD

**Issue by olleolleolle** [barsoom/attr_extras#41]
> minitest-5.14.1 requires ruby version ~> 2.2, which is incompatible with the current version, ruby 3.0.0p0

**Comment by scalp42** [comment]
It's a minitest issue no attr_extras. Ruby 3 was released today also.

**Comment by olleolleolle** [comment]
Hah, I was all confused. No issue here!
